parameters:
#    cliq_org_user.example.class: CliqOrg\UserBundle\Example

services:
#    cliq_org_user.example:
#        class: %cliq_org_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
